name: docker image dt-object-detection-training

on: [push]

jobs:

  build_cpu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Init and update git submodules
        run: cd dt-object-detection-training && git submodule update && pwd && ls tf
      - name: Build the Docker CPU image
        run: docker build -t mstoelzle/dt-object-detection-training:latest dt-object-detection-training/
      - name: Push the Docker CPU image
        run: docker push mstoelzle/dt-object-detection-training:latest

  build_gpu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Init and update git submodules
        run: cd dt-object-detection-training && pwd && git submodule init && ls tf
      - name: Build the Docker GPU image
        run: docker build --build-arg GPU=-gpu -t mstoelzle/dt-object-detection-training:latest-gpu dt-object-detection-training/
      - name: Push the Docker GPU image
        run: docker push mstoelzle/dt-object-detection-training:latest-gpu
