name: docker image dt-object-detection-training

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      env:
        DOCKER_USERNAME: secrets.DOCKER_USERNAME
        DOCKER_PASSWORD: secrets.DOCKER_PASSWORD
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t mstoelzle/dt-object-detection-training:latest dt-object-detection-training/
    - name: Push the Docker image
      run: docker push mstoelzle/dt-object-detection-training:latest
